apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer # Change from NodePort to LoadBalancer
  ports:
    - port: 80        # The port that will be exposed externally (HTTP standard port)
      targetPort: 8000 # The port on which your Flask app is running inside the container
      protocol: TCP
  selector:
    app: flask-app # This should match the label in your deployment